server:
          port: 666

spring:
  application:
    name: product666


  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}

management:
  endpoint:
    web:
      exposure:
        include:*